package com.example.android.vilniusguide;

import android.content.Context;

import java.util.ArrayList;

/**
 * Created by Greta Grigutė on 2018-04-16.
 */

public class Utils {
    // For saving instance state
    public static final String STATE_CURRENT_PAGE = "currentPage";

    //For describing category
    public static final int ARCHITECTURE = 1;
    public static final int SCULPTURE = 2;
    public static final int WALKS = 3;
    public static final int CINEMA = 4;
    public static final int EAT = 5;
    public static final int SHOPPING = 6;

    //Arraylist for top3 objects
    public static final ArrayList<Top> top3 = new ArrayList<>();
    //Create a string ArrayList with all objects.
    public static final ArrayList<Object> objects = new ArrayList<>();
    // Create a list of top 3 objects

    public static ArrayList<Top> getTop3(Context context) {
        if (top3.size() == 0)
            Top3Data(context);
        return top3;
    }

    private static void Top3Data(Context context) {
        top3.add(new Top(context.getString(R.string.arch_object_name_1), R.drawable.arch_1_cathedral_des_bw));
        top3.add(new Top(context.getString(R.string.arch_object_name_2), R.drawable.arch_2_sts_bartholomews_church_des_bw));
        top3.add(new Top(context.getString(R.string.arch_object_name_3), R.drawable.arch_3_bernardine_church1_des_bw));
    }

    public static ArrayList<Object> getObjects(Context context) {
        if (objects.size() == 0)
            ObjectData(context);
        return objects;
    }

    private static void ObjectData(Context context) {
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_1),
                context.getString(R.string.arch_place_1),
                R.drawable.arch_1_cathedral_bw,
                context.getString(R.string.arch_official_link_1),
                context.getString(R.string.arch_description_1),
                context.getString(R.string.arch_resources_1),
                context.getString(R.string.arch_google_link_1),
                R.drawable.arch_1_cathedral_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_2),
                context.getString(R.string.arch_place_2),
                R.drawable.arch_2_sts_bartholomews_church_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.arch_description_2),
                context.getString(R.string.arch_resources_2),
                context.getString(R.string.arch_google_link_2),
                R.drawable.arch_2_sts_bartholomews_church_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_3),
                context.getString(R.string.arch_place_3),
                R.drawable.arch_3_bernardine_church_bw,
                context.getString(R.string.arch_official_link_3),
                context.getString(R.string.arch_description_3),
                context.getString(R.string.arch_resources_3),
                context.getString(R.string.arch_google_link_3),
                R.drawable.arch_3_bernardine_church1_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_4),
                context.getString(R.string.arch_place_4),
                R.drawable.arch_4_jonu_church_bw,
                context.getString(R.string.arch_official_link_4),
                context.getString(R.string.arch_description_4),
                context.getString(R.string.arch_resources_4),
                context.getString(R.string.arch_google_link_4),
                R.drawable.arch_4_jonu_church_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_5),
                context.getString(R.string.arch_place_5),
                R.drawable.arch_5_annas_church_bw,
                context.getString(R.string.arch_official_link_5),
                context.getString(R.string.arch_description_5),
                context.getString(R.string.arch_resources_5),
                context.getString(R.string.arch_google_link_5),
                R.drawable.arch_5_annas_church_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_6),
                context.getString(R.string.arch_place_6),
                R.drawable.arch_1_cathedral_bw,
                context.getString(R.string.arch_official_link_6),
                context.getString(R.string.arch_description_6),
                context.getString(R.string.arch_resources_6),
                context.getString(R.string.arch_google_link_6),
                R.drawable.arch_1_cathedral_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_7),
                context.getString(R.string.arch_place_7),
                R.drawable.arch_7_russian_church_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.arch_description_7),
                context.getString(R.string.arch_resources_7),
                context.getString(R.string.arch_google_link_7),
                R.drawable.arch_7_russian_church_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_8),
                context.getString(R.string.arch_place_8),
                R.drawable.arch_8_grand_dukes_palace_bw,
                context.getString(R.string.arch_official_link_8),
                context.getString(R.string.arch_description_8),
                context.getString(R.string.arch_resources_8),
                context.getString(R.string.arch_google_link_8),
                R.drawable.arch_8_grand_dukes_palace_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_9),
                context.getString(R.string.arch_place_9),
                R.drawable.arch_9_town_hall_bw,
                context.getString(R.string.arch_official_link_9),
                context.getString(R.string.arch_description_9),
                context.getString(R.string.arch_resources_9),
                context.getString(R.string.arch_google_link_9),
                R.drawable.arch_9_town_hall_des_bw));
        objects.add(new Object(ARCHITECTURE,
                context.getString(R.string.arch_object_name_10),
                context.getString(R.string.arch_place_10),
                R.drawable.arch_10_bastion_bw,
                context.getString(R.string.arch_official_link_10),
                context.getString(R.string.arch_description_10),
                context.getString(R.string.arch_resources_10),
                context.getString(R.string.arch_google_link_10),
                R.drawable.arch_10_bastion_des_bw));

        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_1),
                context.getString(R.string.sculpt_place_1),
                R.drawable.dummy_sq,
                context.getString(R.string.sculpt_official_link_1),
                context.getString(R.string.sculpt_description_1),
                context.getString(R.string.sculpt_resources_1),
                context.getString(R.string.sculpt_google_link_1),
                R.drawable.dummy));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_2),
                context.getString(R.string.sculpt_place_2),
                R.drawable.sculpt_2_gediminas_bw,
                context.getString(R.string.sculpt_official_link_2),
                context.getString(R.string.sculpt_description_2),
                context.getString(R.string.sculpt_resources_2),
                context.getString(R.string.sculpt_google_link_2),
                R.drawable.sculpt_2_gediminas_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_3),
                context.getString(R.string.sculpt_place_3),
                R.drawable.dummy_sq,
                context.getString(R.string.sculpt_official_link_3),
                context.getString(R.string.sculpt_description_3),
                context.getString(R.string.sculpt_resources_3),
                context.getString(R.string.sculpt_google_link_3),
                R.drawable.dummy));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_4),
                context.getString(R.string.sculpt_place_4),
                R.drawable.sculpt_4_uzupis_mermaid_bw,
                context.getString(R.string.sculpt_official_link_4),
                context.getString(R.string.sculpt_description_4),
                context.getString(R.string.sculpt_resources_4),
                context.getString(R.string.sculpt_google_link_4),
                R.drawable.sculpt_4_uzupis_mermaid_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_5),
                context.getString(R.string.sculpt_place_5),
                R.drawable.sculpt_5three_muses_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.sculpt_description_5),
                context.getString(R.string.sculpt_resources_5),
                context.getString(R.string.sculpt_google_link_5),
                R.drawable.sculpt_5three_muses_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_6),
                context.getString(R.string.sculpt_place_6),
                R.drawable.sculpt_6_uzupis_angel_bw,
                context.getString(R.string.sculpt_official_link_6),
                context.getString(R.string.sculpt_description_6),
                context.getString(R.string.sculpt_resources_6),
                context.getString(R.string.sculpt_google_link_6),
                R.drawable.sculpt_6_uzupis_angel_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_7),
                context.getString(R.string.sculpt_place_7),
                R.drawable.sculpt_7_kudirka_monument_bw,
                context.getString(R.string.sculpt_official_link_7),
                context.getString(R.string.sculpt_description_7),
                context.getString(R.string.sculpt_resources_7),
                context.getString(R.string.sculpt_google_link_7),
                R.drawable.sculpt_7_kudirka_monument_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_8),
                context.getString(R.string.sculpt_place_8),
                R.drawable.sculpt_8_lamplighter_bw,
                context.getString(R.string.sculpt_official_link_8),
                context.getString(R.string.sculpt_description_8),
                context.getString(R.string.sculpt_resources_8),
                context.getString(R.string.sculpt_google_link_8),
                R.drawable.sculpt_8_lamplighter_des_bw));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_9),
                context.getString(R.string.sculpt_place_9),
                R.drawable.dummy_sq,
                context.getString(R.string.sculpt_official_link_9),
                context.getString(R.string.sculpt_description_9),
                context.getString(R.string.sculpt_resources_9),
                context.getString(R.string.sculpt_google_link_9),
                R.drawable.dummy));
        objects.add(new Object(SCULPTURE,
                context.getString(R.string.sculpt_object_name_10),
                context.getString(R.string.sculpt_place_10),
                R.drawable.sculpt_10_lithuanian_hounds_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.sculpt_description_10),
                context.getString(R.string.sculpt_resources_10),
                context.getString(R.string.sculpt_google_link_10),
                R.drawable.sculpt_10_lithuanian_hounds_des_bw));

        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_1),
                context.getString(R.string.walks_place_1),
                R.drawable.walks_1_pilies_str_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.walks_description_1),
                context.getString(R.string.walks_resources_1),
                context.getString(R.string.walks_google_link_1),
                R.drawable.walks_1_pilies_str_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_2),
                context.getString(R.string.walks_place_2),
                R.drawable.walks_2_gediminas_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.walks_description_2),
                context.getString(R.string.walks_resources_2),
                context.getString(R.string.walks_google_link_2),
                R.drawable.walks_2_gediminas_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_3),
                context.getString(R.string.walks_place_3),
                R.drawable.walks_3_literatu_street_bw,
                context.getString(R.string.walks_official_link_3),
                context.getString(R.string.walks_description_1),
                context.getString(R.string.walks_resources_1),
                context.getString(R.string.walks_google_link_1),
                R.drawable.walks_3_literatu_street_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_4),
                context.getString(R.string.walks_place_4),
                R.drawable.walks_4_cathedral_belltower_bw,
                context.getString(R.string.walks_official_link_4),
                context.getString(R.string.walks_description_4),
                context.getString(R.string.walks_resources_4),
                context.getString(R.string.walks_google_link_4),
                R.drawable.walks_4_cathedral_belltower_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_5),
                context.getString(R.string.walks_place_5),
                R.drawable.walks_5_gediminas_tower_bw,
                context.getString(R.string.walks_official_link_5),
                context.getString(R.string.walks_description_5),
                context.getString(R.string.walks_resources_5),
                context.getString(R.string.walks_google_link_5),
                R.drawable.walks_5_gediminas_tower_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_6),
                context.getString(R.string.walks_place_6),
                R.drawable.walks_6_three_croses_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.walks_description_6),
                context.getString(R.string.walks_resources_6),
                context.getString(R.string.walks_google_link_6),
                R.drawable.walks_6_three_croses_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_7),
                context.getString(R.string.walks_place_7),
                R.drawable.walks_7_vu_garden_bw,
                context.getString(R.string.walks_official_link_7),
                context.getString(R.string.walks_description_7),
                context.getString(R.string.walks_resources_7),
                context.getString(R.string.walks_google_link_7),
                R.drawable.walks_7_vu_garden_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_8),
                context.getString(R.string.walks_place_8),
                R.drawable.walks_8_bernardine_gardens_bw,
                context.getString(R.string.walks_official_link_8),
                context.getString(R.string.walks_description_8),
                context.getString(R.string.walks_resources_8),
                context.getString(R.string.walks_google_link_8),
                R.drawable.walks_8_bernardine_gardens_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_9),
                context.getString(R.string.walks_place_9),
                R.drawable.walks_9_vingis_park_bw,
                context.getString(R.string.walks_official_link_9),
                context.getString(R.string.walks_description_9),
                context.getString(R.string.walks_resources_9),
                context.getString(R.string.walks_google_link_9),
                R.drawable.walks_9_vingis_park_des_bw));
        objects.add(new Object(WALKS,
                context.getString(R.string.walks_object_name_10),
                context.getString(R.string.walks_place_10),
                R.drawable.walks_10_pavilniai_bw,
                context.getString(R.string.walks_official_link_10),
                context.getString(R.string.walks_description_10),
                context.getString(R.string.walks_resources_10),
                context.getString(R.string.walks_google_link_10),
                R.drawable.walks_10_pavilniai_des_bw));

        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_1),
                context.getString(R.string.cinema_place_1),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_1),
                context.getString(R.string.cinema_resources_1),
                context.getString(R.string.cinema_google_link_1),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_2),
                context.getString(R.string.cinema_place_2),
                R.drawable.cin_2_drama_theatre_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_2),
                context.getString(R.string.cinema_resources_2),
                context.getString(R.string.cinema_google_link_2),
                R.drawable.cin_2_drama_theatre_des_bw));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_3),
                context.getString(R.string.cinema_place_3),
                R.drawable.cin_3_arts_printing_house_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_3),
                context.getString(R.string.cinema_resources_3),
                context.getString(R.string.cinema_google_link_3),
                R.drawable.cin_3_arts_printing_house_des_bw));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_4),
                context.getString(R.string.cinema_place_4),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_4),
                context.getString(R.string.cinema_resources_4),
                context.getString(R.string.cinema_google_link_4),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_5),
                context.getString(R.string.cinema_place_5),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_5),
                context.getString(R.string.cinema_resources_5),
                context.getString(R.string.cinema_google_link_5),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_6),
                context.getString(R.string.cinema_place_6),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_6),
                context.getString(R.string.cinema_resources_6),
                context.getString(R.string.cinema_google_link_6),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_7),
                context.getString(R.string.cinema_place_7),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_7),
                context.getString(R.string.cinema_resources_7),
                context.getString(R.string.cinema_google_link_7),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_8),
                context.getString(R.string.cinema_place_8),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_8),
                context.getString(R.string.cinema_resources_8),
                context.getString(R.string.cinema_google_link_8),
                R.drawable.dummy));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_9),
                context.getString(R.string.cinema_place_9),
                R.drawable.cin_9_pasaka_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_9),
                context.getString(R.string.cinema_resources_9),
                context.getString(R.string.cinema_google_link_9),
                R.drawable.cin_9_pasaka_des_bw));
        objects.add(new Object(CINEMA,
                context.getString(R.string.cinema_object_name_10),
                context.getString(R.string.cinema_place_10),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.cinema_description_10),
                context.getString(R.string.cinema_resources_10),
                context.getString(R.string.cinema_google_link_10),
                R.drawable.dummy));

        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_1),
                context.getString(R.string.eat_place_1),
                R.drawable.eat_1_boom_burgers_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_1),
                context.getString(R.string.eat_resources_1),
                context.getString(R.string.eat_google_link_1),
                R.drawable.eat_1_boom_burgers_des_bw));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_2),
                context.getString(R.string.eat_place_2),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_2),
                context.getString(R.string.eat_resources_2),
                context.getString(R.string.eat_google_link_2),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_3),
                context.getString(R.string.eat_place_3),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_3),
                context.getString(R.string.eat_resources_3),
                context.getString(R.string.eat_google_link_3),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_4),
                context.getString(R.string.eat_place_4),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_4),
                context.getString(R.string.eat_resources_4),
                context.getString(R.string.eat_google_link_4),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_5),
                context.getString(R.string.eat_place_5),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_5),
                context.getString(R.string.eat_resources_5),
                context.getString(R.string.eat_google_link_5),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_6),
                context.getString(R.string.eat_place_6),
                R.drawable.eat_6_la_boheme_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_6),
                context.getString(R.string.eat_resources_6),
                context.getString(R.string.eat_google_link_6),
                R.drawable.eat_6_la_boheme_des_bw));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_7),
                context.getString(R.string.eat_place_7),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_7),
                context.getString(R.string.eat_resources_7),
                context.getString(R.string.eat_google_link_7),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_8),
                context.getString(R.string.eat_place_8),
                R.drawable.dummy_sq,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_8),
                context.getString(R.string.eat_resources_8),
                context.getString(R.string.eat_google_link_8),
                R.drawable.dummy));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_9),
                context.getString(R.string.eat_place_9),
                R.drawable.eat_9_uzupio_pizza_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_9),
                context.getString(R.string.eat_resources_9),
                context.getString(R.string.eat_google_link_9),
                R.drawable.eat_9_uzupio_pizza_des_bw));
        objects.add(new Object(EAT,
                context.getString(R.string.eat_object_name_10),
                context.getString(R.string.eat_place_10),
                R.drawable.eat_10_town_restaurant_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.eat_description_10),
                context.getString(R.string.eat_resources_10),
                context.getString(R.string.eat_google_link_10),
                R.drawable.eat_10_town_restaurant_des_bw));

        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_1),
                context.getString(R.string.shop_place_1),
                R.drawable.shop_1_ozas_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_1),
                context.getString(R.string.shop_resources_1),
                context.getString(R.string.shop_google_link_1),
                R.drawable.shop_1_ozas_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_2),
                context.getString(R.string.shop_place_2),
                R.drawable.shop_2_akropolis_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_2),
                context.getString(R.string.shop_resources_2),
                context.getString(R.string.shop_google_link_2),
                R.drawable.shop_2_akropolis_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_3),
                context.getString(R.string.shop_place_3),
                R.drawable.shop_3_panorama_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_3),
                context.getString(R.string.shop_resources_3),
                context.getString(R.string.shop_google_link_3),
                R.drawable.shop_3_panorama_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_4),
                context.getString(R.string.shop_place_4),
                R.drawable.shop_4_europa_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_4),
                context.getString(R.string.shop_resources_4),
                context.getString(R.string.shop_google_link_4),
                R.drawable.shop_4_europa_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_5),
                context.getString(R.string.shop_place_5),
                R.drawable.shop_5_ogmios_city_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_5),
                context.getString(R.string.shop_resources_5),
                context.getString(R.string.shop_google_link_5),
                R.drawable.shop_5_ogmios_city_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_6),
                context.getString(R.string.shop_place_6),
                R.drawable.shop_6_go_9_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_6),
                context.getString(R.string.shop_resources_6),
                context.getString(R.string.shop_google_link_6),
                R.drawable.shop_6_go_9_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_7),
                context.getString(R.string.shop_place_7),
                R.drawable.shop_7_v_cup_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_7),
                context.getString(R.string.shop_resources_7),
                context.getString(R.string.shop_google_link_7),
                R.drawable.shop_7_v_cup_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_8),
                context.getString(R.string.shop_place_8),
                R.drawable.shop_8_big_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_8),
                context.getString(R.string.shop_resources_8),
                context.getString(R.string.shop_google_link_8),
                R.drawable.shop_8_big_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_9),
                context.getString(R.string.shop_place_9),
                R.drawable.shop_9_mada_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_9),
                context.getString(R.string.shop_resources_9),
                context.getString(R.string.shop_google_link_9),
                R.drawable.shop_9_mada_des_bw));
        objects.add(new Object(SHOPPING,
                context.getString(R.string.shop_object_name_10),
                context.getString(R.string.shop_place_10),
                R.drawable.shop_10_hales_bw,
                context.getString(R.string.no_link),
                context.getString(R.string.shop_description_10),
                context.getString(R.string.shop_resources_10),
                context.getString(R.string.shop_google_link_10),
                R.drawable.shop_10_hales_des_bw));
    }
}


